- md/terminusx/start-with-a-client.md
> Update Python codes

- md/reference/reference-schema.md
> updated enum documentation

- md/terminusx/start-with-a-client.md
> added query with woql section

- readme/terminusdb/install/install-from-source-code.md
Fix wrong installation of clang and description of why it is needed
> Clang issue

- .gitbook.yaml
- README.md
- index.md
- summary.md
* Rename GitBook `README.md` to `index.md`
* Rename `SUMMARY.md` to `summary.md`
This should be confirmed to work in GitBook before merging.
> Add README.md for GitHub view

- index/json-diff-and-patch.md
It is clearer now what is the expected output and what's part of the command and also it does not expect input from stdin
> Improve curl examples

- index/json-diff-and-patch.md
> Use public endpoint for docs

- index/terminusx-db/reference-guides/javascript-client-reference/accesscontrol.md
- index/terminusx-db/reference-guides/javascript-client-reference/typedef.md
- index/terminusx-db/reference-guides/javascript-client-reference/woql.md
- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
- index/terminusx-db/reference-guides/javascript-client-reference/woqllibrary.md
JS-Reference-Updates-1649000490
> JS-Reference-Updates-1649000490

- index/terminusx-db/reference-guides/javascript-client-reference/woql.md
- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1649234510
> JS-Reference-Updates-1649234510

- index/terminusx-db/reference-guides/javascript-client-reference/typedef.md
- index/terminusx-db/reference-guides/javascript-client-reference/woql.md
- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1652466026
> JS-Reference-Updates-1652466026

- readme/terminusx-db/reference-guides/http-api.md
Add new user management endpoints
> Update API documentation

- index/terminusx-db/reference-guides/javascript-client-reference/accesscontrol.md
- index/terminusx-db/reference-guides/javascript-client-reference/typedef.md
- index/terminusx-db/reference-guides/javascript-client-reference/woql.md
- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1660298770
> JS-Reference-Updates-1660298770

- index/terminusx-db/reference-guides/javascript-client-reference/typedef.md
- index/terminusx-db/reference-guides/javascript-client-reference/woql.md
- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1661166430
> JS-Reference-Updates-1661166430

- index/terminusx-db/reference-guides/python-client-reference/index.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.client.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.schema.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.scripts.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.tests.integration_tests.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.tests.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.tests.woqljson.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqlclient.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqldataframe.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqlquery.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqlschema.md
Python-Reference-Updates-1661262425
> Python-Reference-Updates-1661262425

- index/terminusx-db/reference-guides/python-client-reference/index.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.client.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.schema.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.scripts.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.tests.integration_tests.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.tests.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.tests.woqljson.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqlclient.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqldataframe.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqlquery.md
- index/terminusx-db/reference-guides/python-client-reference/terminusdb_client.woqlschema.md
Python-Reference-Updates-1661264567
> Python-Reference-Updates-1661264567

- index/terminusx-db/reference-guides/python-client-reference/README.md
- index/terminusx-db/reference-guides/python-client-reference/Scaffolding_CLI_Tool.md
Python-Reference-Updates-1661265788
> Python-Reference-Updates-1661265788

- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1661332767
> JS-Reference-Updates-1661332767

- index/terminusx-db/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1661354456
> JS-Reference-Updates-1661354456

- guides/reference-guides/javascript-client-reference/accesscontrol.md
- guides/reference-guides/javascript-client-reference/typedef.md
- guides/reference-guides/javascript-client-reference/woql.md
- guides/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1668678457
> JS-Reference-Updates-1668678457

- guides/reference-guides/javascript-client-reference/typedef.md
- guides/reference-guides/javascript-client-reference/woql.md
- guides/reference-guides/javascript-client-reference/woqlclient.md
JS-Reference-Updates-1672763632
> JS-Reference-Updates-1672763632

- guides/reference-guides/schema.md
Added unfoldable to the existing documentation.
IMO this doc needs some reworking but for now this will at least make it more complete.
> Add unfoldable to schema reference
